/**
 * Built-in Layout Presets for Custom Touch Layout Studio.
 */

import { CustomLayout } from './types';
import { GamepadButtonBit } from '@lookaremote/protocol-types';

export const DEFAULT_XBOX_LAYOUT: CustomLayout = {
  id: 'preset-xbox-default',
  name: 'Standard Xbox Dual-Stick',
  description: 'Classic dual analog sticks, ABXY diamond cluster, D-Pad, Bumpers, and Triggers.',
  orientation: 'landscape',
  gridSnap: 16,
  isPreset: true,
  createdAt: 1724700000000,
  updatedAt: 1724700000000,
  elements: [
    // Left Thumbstick
    {
      id: 'elem-stick-l',
      type: 'stick',
      label: 'LS',
      x: 48,
      y: 180,
      width: 140,
      height: 140,
      color: '#00E5FF',
      mapping: { axisX: 'stick_lx', axisY: 'stick_ly', buttonBit: GamepadButtonBit.THUMB_L },
    },
    // D-Pad
    {
      id: 'elem-dpad',
      type: 'dpad',
      label: 'D-Pad',
      x: 190,
      y: 200,
      width: 120,
      height: 120,
      color: '#00E5FF',
      mapping: {},
    },
    // Left Trigger / Bumper
    {
      id: 'elem-btn-lb',
      type: 'button',
      label: 'LB',
      x: 48,
      y: 60,
      width: 90,
      height: 50,
      color: '#00E5FF',
      mapping: { buttonBit: GamepadButtonBit.SHOULDER_L },
    },
    {
      id: 'elem-trig-lt',
      type: 'trigger',
      label: 'LT',
      x: 150,
      y: 60,
      width: 90,
      height: 50,
      color: '#00E5FF',
      mapping: { triggerSide: 'left' },
    },
    // Center Menu / View
    {
      id: 'elem-btn-view',
      type: 'button',
      label: 'VIEW',
      x: 320,
      y: 60,
      width: 60,
      height: 40,
      color: '#8B949E',
      mapping: { buttonBit: GamepadButtonBit.SELECT },
    },
    {
      id: 'elem-btn-menu',
      type: 'button',
      label: 'MENU',
      x: 420,
      y: 60,
      width: 60,
      height: 40,
      color: '#8B949E',
      mapping: { buttonBit: GamepadButtonBit.START },
    },
    // Right Thumbstick
    {
      id: 'elem-stick-r',
      type: 'stick',
      label: 'RS',
      x: 520,
      y: 200,
      width: 140,
      height: 140,
      color: '#00E5FF',
      mapping: { axisX: 'stick_rx', axisY: 'stick_ry', buttonBit: GamepadButtonBit.THUMB_R },
    },
    // Right Trigger / Bumper
    {
      id: 'elem-trig-rt',
      type: 'trigger',
      label: 'RT',
      x: 560,
      y: 60,
      width: 90,
      height: 50,
      color: '#00E5FF',
      mapping: { triggerSide: 'right' },
    },
    {
      id: 'elem-btn-rb',
      type: 'button',
      label: 'RB',
      x: 660,
      y: 60,
      width: 90,
      height: 50,
      color: '#00E5FF',
      mapping: { buttonBit: GamepadButtonBit.SHOULDER_R },
    },
    // ABXY Cluster
    {
      id: 'elem-btn-y',
      type: 'button',
      label: 'Y',
      x: 690,
      y: 140,
      width: 55,
      height: 55,
      color: '#FFE600',
      mapping: { buttonBit: GamepadButtonBit.NORTH },
    },
    {
      id: 'elem-btn-x',
      type: 'button',
      label: 'X',
      x: 630,
      y: 195,
      width: 55,
      height: 55,
      color: '#00E5FF',
      mapping: { buttonBit: GamepadButtonBit.WEST },
    },
    {
      id: 'elem-btn-b',
      type: 'button',
      label: 'B',
      x: 750,
      y: 195,
      width: 55,
      height: 55,
      color: '#FF007F',
      mapping: { buttonBit: GamepadButtonBit.EAST },
    },
    {
      id: 'elem-btn-a',
      type: 'button',
      label: 'A',
      x: 690,
      y: 250,
      width: 55,
      height: 55,
      color: '#00FF66',
      mapping: { buttonBit: GamepadButtonBit.SOUTH },
    },
  ],
};

export const FPS_CLAW_LAYOUT: CustomLayout = {
  id: 'preset-fps-claw',
  name: 'FPS 4-Finger Claw',
  description: 'Optimized for high-mobility competitive FPS: rapid Jump/Slide macros and top bumpers.',
  orientation: 'landscape',
  gridSnap: 16,
  isPreset: true,
  createdAt: 1724700000000,
  updatedAt: 1724700000000,
  elements: [
    {
      id: 'elem-stick-l',
      type: 'stick',
      label: 'Move',
      x: 40,
      y: 170,
      width: 150,
      height: 150,
      color: '#00E5FF',
      mapping: { axisX: 'stick_lx', axisY: 'stick_ly', buttonBit: GamepadButtonBit.THUMB_L },
    },
    {
      id: 'elem-btn-lb',
      type: 'button',
      label: 'Aim (LB)',
      x: 40,
      y: 40,
      width: 110,
      height: 60,
      color: '#00E5FF',
      mapping: { buttonBit: GamepadButtonBit.SHOULDER_L },
    },
    {
      id: 'elem-btn-jump-macro',
      type: 'macro',
      label: '⚡ Bunny Hop',
      x: 160,
      y: 40,
      width: 110,
      height: 60,
      color: '#FFE600',
      mapping: {
        macroSequence: [GamepadButtonBit.SOUTH, 0, GamepadButtonBit.SOUTH, 0],
        macroStepDelayMs: 40,
      },
    },
    {
      id: 'elem-stick-r',
      type: 'stick',
      label: 'Look',
      x: 500,
      y: 170,
      width: 150,
      height: 150,
      color: '#FF007F',
      mapping: { axisX: 'stick_rx', axisY: 'stick_ry', buttonBit: GamepadButtonBit.THUMB_R },
    },
    {
      id: 'elem-btn-turbo-fire',
      type: 'turbo',
      label: '🔥 Turbo Fire',
      x: 670,
      y: 40,
      width: 110,
      height: 60,
      color: '#FF0055',
      mapping: { buttonBit: GamepadButtonBit.SHOULDER_R, turboRateHz: 20 },
    },
    {
      id: 'elem-btn-crouch',
      type: 'button',
      label: 'Slide (B)',
      x: 680,
      y: 150,
      width: 80,
      height: 60,
      color: '#00FF66',
      mapping: { buttonBit: GamepadButtonBit.EAST },
    },
    {
      id: 'elem-btn-reload',
      type: 'button',
      label: 'Reload (X)',
      x: 680,
      y: 230,
      width: 80,
      height: 60,
      color: '#00E5FF',
      mapping: { buttonBit: GamepadButtonBit.WEST },
    },
  ],
};

export const FIGHTING_ARCADE_LAYOUT: CustomLayout = {
  id: 'preset-fighting-arcade',
  name: '6-Button Arcade Fighter',
  description: 'Arcade stick + 6 action buttons (LP/MP/HP, LK/MK/HK) and instant Super combo macros.',
  orientation: 'landscape',
  gridSnap: 16,
  isPreset: true,
  createdAt: 1724700000000,
  updatedAt: 1724700000000,
  elements: [
    {
      id: 'elem-dpad',
      type: 'dpad',
      label: 'Arcade D-Pad',
      x: 50,
      y: 140,
      width: 160,
      height: 160,
      color: '#FFE600',
      mapping: {},
    },
    // Top Row: LP, MP, HP
    {
      id: 'elem-lp',
      type: 'button',
      label: 'LP (X)',
      x: 480,
      y: 100,
      width: 70,
      height: 70,
      color: '#00E5FF',
      mapping: { buttonBit: GamepadButtonBit.WEST },
    },
    {
      id: 'elem-mp',
      type: 'button',
      label: 'MP (Y)',
      x: 570,
      y: 90,
      width: 70,
      height: 70,
      color: '#FFE600',
      mapping: { buttonBit: GamepadButtonBit.NORTH },
    },
    {
      id: 'elem-hp',
      type: 'button',
      label: 'HP (RB)',
      x: 660,
      y: 100,
      width: 70,
      height: 70,
      color: '#FF007F',
      mapping: { buttonBit: GamepadButtonBit.SHOULDER_R },
    },
    // Bottom Row: LK, MK, HK
    {
      id: 'elem-lk',
      type: 'button',
      label: 'LK (A)',
      x: 480,
      y: 200,
      width: 70,
      height: 70,
      color: '#00FF66',
      mapping: { buttonBit: GamepadButtonBit.SOUTH },
    },
    {
      id: 'elem-mk',
      type: 'button',
      label: 'MK (B)',
      x: 570,
      y: 190,
      width: 70,
      height: 70,
      color: '#FF0055',
      mapping: { buttonBit: GamepadButtonBit.EAST },
    },
    {
      id: 'elem-hk',
      type: 'button',
      label: 'HK (RT)',
      x: 660,
      y: 200,
      width: 70,
      height: 70,
      color: '#9900FF',
      mapping: { triggerSide: 'right' },
    },
    // Hadouken / Super Combo Macro
    {
      id: 'elem-hadouken',
      type: 'macro',
      label: '⚡ Hadouken Combo',
      x: 250,
      y: 240,
      width: 140,
      height: 55,
      color: '#00E5FF',
      mapping: {
        macroSequence: [
          GamepadButtonBit.DPAD_DOWN,
          GamepadButtonBit.DPAD_DOWN | GamepadButtonBit.DPAD_RIGHT,
          GamepadButtonBit.DPAD_RIGHT | GamepadButtonBit.WEST,
        ],
        macroStepDelayMs: 30,
      },
    },
  ],
};

export const BUILTIN_PRESETS: CustomLayout[] = [
  DEFAULT_XBOX_LAYOUT,
  FPS_CLAW_LAYOUT,
  FIGHTING_ARCADE_LAYOUT,
];
